### ISSUE TITLE
Npm package?

### ISSUE THREAD

**Issue by benheb** [garfieldduck/react-scrolly#16]
What's the best way to use this, is it published somewhere?

**Comment by garfieldduck** [comment]
Hey @benheb,
Sorry for the late reply. This is designed for the needs of the performant [scrollytelling](https://webflow.com/blog/scrollytelling-guide), or pages with a lot of scroll-triggered effects.
However, it's only used on my personal projects currently, and I haven't publicized it.

If you are still interested in testing it out, it's published on npm.
https://www.npmjs.com/search?q=%40react-scrolly

The usage is documented in: https://garfieldduck.github.io/react-scrolly/
